version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      ALPHA_VANTAGE_API_KEY: 
      POSTGRES_DB: mydb
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_DEBUG: 'True'  #develop mode
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: mydb 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:
