# Generated by Django 5.1.2 on 2024-10-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_prediction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='stockdata',
            name='myapp_stock_symbol_ae9983_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='high_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='low_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
