name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build . -t YOUR_USER/myproject
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u  YOUR_USER --password-stdin
          docker push YOUR_USER/myproject

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@98.80.250.179 'docker pull YOUR_USER/myproject && docker-compose up -d'

