name: Despliegue Django

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas
      run: |
        python manage.py test

    - name: Construir y subir imagen Docker a Docker Hub
      run: |
        docker build . -t sabrinadev/myproject
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u <tu-usuario-dockerhub> --password-stdin
        docker push <tu-usuario-dockerhub>/myproject

    - name: Desplegar en AWS EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@<tu_ip_ec2> 'docker pull <tu-usuario-dockerhub>/myproject && docker-compose up -d'
